### ISSUE TITLE
Pilot

### ISSUE THREAD

**Issue by 0mBudsMan** [opencodeiiita/Scoop-Frontend#1]
Create a logo for Scoop website.

Ensure that the logo concept reflects the core function of the website – sharing news. Incorporate symbols or imagery related to communication, sharing, or news dissemination

Keep the design simple and easily recognizable. A clutter-free logo is more memorable and versatile across different platforms and sizes.

Choose colors that convey trust, reliability, and professionalism. Common choices for news-related logos include blue (trust), red (urgency/alert), or black (sophistication). 

Once you have created it, include the url (figma, canva or wherever your is created) in design.json file. An example of how you can do that is already in the file, do look it.

Time: 24 hours

**Comment by D-Hacker26** [comment]
approved

**Comment by Ashutosh9993** [comment]
Claim

**Comment by 0mBudsMan** [comment]
Ashutosh, you don't need to claim these types of issues! This is open-for-all, as the label suggests. After 24 hours, best entries will be selected and points will be assigned. Others may get partial points

**Comment by 0mBudsMan** [comment]
> approved

Thanks sir

**Comment by VrajShah34** [comment]
When will the points be awarded? And why is the issue still bring kept open well after 24 hrs??
