### ISSUE TITLE
Redux Toolkit for News

### ISSUE THREAD

**Issue by 0mBudsMan** [opencodeiiita/Scoop-Frontend#105]
# Task: Enhance Scoop Composition Form and Implement Redux Toolkit for News

### Goal
Enhance the existing frontend (composeScoopPage.js) for composing a scoop by adding options for tags and a header image. Additionally, use Redux Toolkit to send scoop (news) details to the database. Implement Redux Toolkit functionality for receiving top news, latest news, and credible news. Display such news in already existing page (/pages/allNews)

### Tasks

1. **Enhance Scoop Composition Form**
   - Add options for tags and a header image in the frontend scoop composition form.
   - Ensure that the form captures and sends the added information.

2. **Implement Redux Toolkit for Sending Scoop Details**
   - Utilize Redux Toolkit to manage state for sending scoop details to the database.
   - Implement actions, reducers, and constants for handling the composition process.
   - **_Utilize the existing `authSlice` as a reference for maintaining the code structure._**

3. **Redux Toolkit for Receiving Top News**
   - Implement Redux Toolkit functionality for receiving top news from the backend.
   - Utilize the existing route: `GET /api/scoop/top`.

4. **Redux Toolkit for Receiving Credible News**
   - Implement Redux Toolkit functionality for receiving credible news from the backend.
   - Utilize the existing route: `GET /api/scoop/credible`.

5. **Redux Toolkit for Receiving Latest News**
   - Implement Redux Toolkit functionality for receiving the latest news from the backend.
   - Utilize the existing route: `GET /api/scoop/latest`.

6. **Integrate with Allnews Page**
   - Ensure that the enhancements and Redux Toolkit functionalities integrate seamlessly with the existing page for displaying a list of scoop/news (`pages/Allnews.js`).

### Additional Information
- **_The `authSlice` is already created; you can take help from that to create a new slice for this task. Maintain the code structure as shown in the `authSlice`._**
- The backend routes for receiving top news, credible news, and latest news are already created.
- Make sure to handle success and error scenarios appropriately, dispatching actions based on the API responses.
- Ensure a clean and user-friendly design for the scoop composition form.
- Create your own dummy database, and feed it with dummy users and news to test. Attach ss thereafter.

## Deadline
Please submit your pull request by 36 hours.

https://docs.google.com/document/d/10yP0jaFCSQqCkDxt0LaMta6dvzyRQG3l55ZEXO092do/edit

**Comment by TheDivineAurora** [comment]
claim

**Comment by Apoorv012** [comment]
claim

**Comment by kushal7201** [comment]
Claim

**Comment by Nandinig24** [comment]
Claim

**Comment by Mannxxx** [comment]
Claim

**Comment by aravks** [comment]
Claim

**Comment by 0mBudsMan** [comment]
@TheDivineAurora status?

**Comment by TheDivineAurora** [comment]
im working on it , please give me time

**Comment by LifeAsDev** [comment]
claim

**Comment by Pranav915** [comment]
claim
