### ISSUE TITLE
Home Harmony: Unifying News Sections

### ISSUE THREAD

**Issue by 0mBudsMan** [opencodeiiita/Scoop-Frontend#106]
# Task: Implement Universal Redux Slice for Home Page News Sections

### Goal
Implement a new Redux slice for managing data related to various sections on the home page. Utilize this universal slice to display credible news in the topmost carousel, top news in the top posts category, and the latest news in the corresponding section. Additionally, create a dummy database and populate it with dummy users and news for testing purposes.

### Tasks

1. **Create Universal Redux Slice**
   - Implement a new Redux slice with a structure similar to the existing `authSlice.js` for managing data related to the home page news sections.
   - Define actions, reducers, and constants as needed to handle credible news, top news, and latest news.

2. **Integrate Redux Slice in Home Page Sections**
   - Utilize the new Redux slice to manage data for various sections on the home page.
   - Display credible news in the topmost carousel, top news in the top posts category, and the latest news in the corresponding section.

3. **Create Dummy Database**
   - Set up a dummy database with user and news data for testing purposes.
   - Populate the database with dummy users and news articles.

4. **Take Screenshots of Home Page**
   - After feeding data to the dummy database, take screenshots of the home page to showcase how each section displays news content.

5. **Implement Additional API Endpoints**
   - Implement additional API endpoints for fetching specific data for the home page:
     - `GET /api/scoop/home/top`: Retrieve the top 5 news sorted based on the most number of upvotes on news.
     - `GET /api/scoop/home/credible`: Retrieve the latest news from the top 5 profiles, sorted based on the most number of upvotes on the profile.
     - `GET /api/scoop/home/categories`: Return an array of all tags used in all news, ensuring no duplicate entries.
     - `GET /api/scoop/home/latest`: Return the 5 latest news from the database.

6. **Create Frontend Routes (if needed)**
   - If your application requires additional frontend routes, you can create them using a routing library or framework of your choice.

### Additional Information
- The Redux slice structure should be similar to the existing `authSlice.js` to maintain consistency in code structure.
- Implement the integration of the new Redux slice in various sections of the home page.
- Use the dummy database for testing and ensure that the home page sections display the appropriate news content.

## Submission Guidelines
- Fork the repository and create a branch for this task.
- Create a pull request with the implemented changes.
- Reference this issue in the pull request.
- Attach screenshots of the home page after feeding data to the database.

## Deadline
Please submit your pull request by 36 hours

**Note:** Feel free to ask for any clarifications or assistance during the implementation process.

**Comment by TheDivineAurora** [comment]
claim

**Comment by Mannxxx** [comment]
Claim

**Comment by WadadParker** [comment]
claim

**Comment by Rohit-110** [comment]
Claim

**Comment by Apoorv012** [comment]
C

**Comment by abhisheksharma010** [comment]
Claim

**Comment by 0mBudsMan** [comment]
@Mannxxx link for backend repo: https://github.com/opencodeiiita/Scoop-Backend

**Comment by 0mBudsMan** [comment]
@Mannxxx status?

**Comment by 0mBudsMan** [comment]
@Mannxxx ??

**Comment by Mannxxx** [comment]
How long do I have to make pull request? I'm working on this only.

**Comment by 0mBudsMan** [comment]
@Mannxxx make it by tonight

**Comment by Rohit-110** [comment]
Claim

**Comment by 0mBudsMan** [comment]
@Rohit-110 any blockers? it's past deadline

**Comment by Pranav915** [comment]
claim

**Comment by rnavaneeth992** [comment]
Claim

**Comment by Jarviss77** [comment]
claim

**Comment by CodinJack** [comment]
claim

**Comment by 0mBudsMan** [comment]
@rnavaneeth992 kindly submit pr by tomorrow night

**Comment by Apoorv012** [comment]
claim

**Comment by TheDivineAurora** [comment]
claim

**Comment by poojaindulkar** [comment]
claim
