### ISSUE TITLE
Display User Info in Navbar

### ISSUE THREAD

**Issue by 0mBudsMan** [opencodeiiita/Scoop-Frontend#107]
# Task: Display User Info in Navbar

### Goal
Modify the `authSlice` to save user information in the store upon user registration or login. Update the state to include user information. Implement the display of the user's name and avatar in the navbar if the user is logged in. If the user is not logged in, display a 'Login' option.

### Tasks

1. **Update `authSlice`**
   - Modify the `authSlice` to include additional user information in the state upon successful user registration or login.
   - Ensure that the user data includes the user's name and avatar.
   - Currently, user object in state only has token and isLoggedin.

2. **Update Navbar**
   - In the navbar component, conditionally display the user's name and avatar if a user is logged in.
   - Display a 'Login' option if the user is not logged in.

### Additional Information
- The `authSlice` is already created; you can leverage it to store user information.
- Ensure that the user data is properly updated in the store upon registration or login.
- Use the stored user data to dynamically render the user's name and avatar in the navbar.

## Deadline
Please submit your pull request by 24 hours.

**Note:** Feel free to ask for any clarifications or assistance during the implementation process.

**Comment by Apoorv012** [comment]
Claim

**Comment by kushal7201** [comment]
Claim

**Comment by WadadParker** [comment]
claim
