### ISSUE TITLE
Profile Precision: User Profile from Backend

### ISSUE THREAD

**Issue by 0mBudsMan** [opencodeiiita/Scoop-Frontend#108]
# Task: Create Dynamic Route for User Profile Page

### Goal
Implement a dynamic route for the profile page of a specific user using the pattern `/profile/:profileId`. Utilize the existing profile page component for rendering the user's profile. The backend route for fetching user details is `/api/user/:userId`.

### Tasks

1. **Create Dynamic Route**
   - Set up a dynamic route in your routing configuration to handle the pattern `/profile/:profileId`.

2. **Utilize Existing Profile Page**
   - Make use of the existing profile page component for rendering the user's profile information.
   - Ensure that the profile page dynamically fetches and displays data for the specified user using the backend route `/api/user/:userId`.

### Additional Information
- The profile page component is already created; you can leverage it for displaying user profiles.
- The backend route for fetching user details is `/api/user/:userId`.

## Deadline
Please submit your pull request by 24 hours

**Note:** Feel free to ask for any clarifications or assistance during the implementation process.

**Comment by kushal7201** [comment]
Claim

**Comment by Jarviss77** [comment]
Claim

**Comment by 0mBudsMan** [comment]
@kushal7201 check comment in pr

**Comment by Apoorv012** [comment]
claim

**Comment by Rohit-110** [comment]
Claim

**Comment by 0mBudsMan** [comment]
@Rohit-110 congrats! Kindly be active on discord or reply here

**Comment by Apoorv012** [comment]
claim

**Comment by Parth4git** [comment]
claim

**Comment by Parth4git** [comment]
claim

**Comment by 0mBudsMan** [comment]
@Parth4git , welcome! Do watch for time limit and ping me on discord for any queries

**Comment by k7aditya** [comment]
claim

**Comment by Apoorv012** [comment]
working on it
