### ISSUE TITLE
 Implement React Toast for Sign-in and Registration Pages

### ISSUE THREAD

**Issue by 0mBudsMan** [opencodeiiita/Scoop-Frontend#112]
# Issue: Implement React Toast for Sign-in and Registration Pages

### Problem

The current sign-in and registration pages lack user feedback on the success or failure of the authentication process. To enhance the user experience, we want to implement React Toast notifications to display whether the registration or login is successful. In case of failure, the error should be shown in the toast.

### Goal

The goal is to provide immediate visual feedback to users upon attempting to sign in or register. Toast notifications are a common and effective way to achieve this.

## Tasks

1. **Integrate React Toast Component:**
   - Find a suitable React Toast library or create a custom solution.
   - Integrate the selected solution into the existing sign-in and registration pages.

2. **Display Success Toast:**
   - Show a toast message when `auth.user.isLoggedIn` is `true` after registration or login.

3. **Display Error Toast:**
   - Show a toast message with the error from the `auth` slice's state when there is an authentication error during registration or login.

4. **Styling:**
   - Ensure that the toast messages are visually appealing and consistent with the overall design.

Deadline: 24 hours
## Additional Information

If you have any questions or need clarification, feel free to comment on this issue.

Thank you for your contribution!

**Comment by kushal7201** [comment]
Claim

**Comment by Apoorv012** [comment]
claim

**Comment by 0mBudsMan** [comment]
@kushal7201 you're already assigned 1 issue in this repo

**Comment by 0mBudsMan** [comment]
@Apoorv012 three issues  are already assigned to you, pls confirm whether you've submitted a pr for any of them.

**Comment by Apoorv012** [comment]
I have only 2 issues at the moment

**Comment by Apoorv012** [comment]
One of Donation App, and other of Code-Digger

**Comment by Jarviss77** [comment]
claim

**Comment by 0mBudsMan** [comment]
ok @Apoorv012, make sure you unassign yourself if pr is already merged

**Comment by chiragmalik2612** [comment]
claim
