### ISSUE TITLE
Navigation Nexus - Add a navbar

### ISSUE THREAD

**Issue by 0mBudsMan** [opencodeiiita/Scoop-Frontend#2]
Make a **_RESPONSIVE_** navbar for scoop, as shown in the [**FIGMA**](https://www.figma.com/file/vxtYC3QMgjFJ7WTJiorWJ4/Untitled?type=design&node-id=0-1&mode=design&t=likANEcp5ojPCk8r-0) given in project readme.

- TIME: 12 hours

> Use MUI for the same

> MUI has provided some examples of navbar in their docs [CLICK TO VIEW](https://mui.com/material-ui/react-app-bar/)

> PS: MUI responsive navbars are easily available on internet, you can use any of that to modify it accoridng to figma needs.

- **HAPPY CONTRIBUTING**

**Comment by Jarviss77** [comment]
pls assign

**Comment by 0mBudsMan** [comment]
Issue assigned! Happy contributing! Also, ping on discord for any help!

**Comment by PranavBansal21** [comment]
claim

**Comment by Rudreshdabre12** [comment]
claim

**Comment by shashankpatil28** [comment]
@Jarviss77 Status please.

**Comment by iam-buddhi** [comment]
claim

**Comment by akshatj22** [comment]
plz assign

**Comment by WadadParker** [comment]
claim

**Comment by 0mBudsMan** [comment]
> claim

Kindly make this done by tomorrow!!

**Comment by Ashutosh9993** [comment]
Claim

**Comment by captainflatbelly** [comment]
claim

**Comment by amanrubey** [comment]
Claim

**Comment by kushal7201** [comment]
Claim

**Comment by 0mBudsMan** [comment]
@kushal7201 make this done by tonight! All the best

**Comment by kushal7201** [comment]
OK
