### ISSUE TITLE
Category Cards' carousel

### ISSUE THREAD

**Issue by 0mBudsMan** [opencodeiiita/Scoop-Frontend#3]
**TIME: 48 hours**

- Refer [**FIGMA**](https://www.figma.com/file/jAKJY9AhyIxhl1IloKacbY/Free-News-%26-Magazine-Figma-Template-%2F-All-pages-(Community)?type=design&node-id=18-29&mode=design&t=faD1LQWa0wLh0eHh-0)
- In desktop view, below the navbar, there are some cards below navbar
- Implement that for different categories (Categories are already given an array in component file (src/components/CardsCarousel.js)
- For background image, use any random image from unspash
- Use MUI for the task
- Carousel and cards using MUI can easily be found on the web, use that and shape it according to the given design temeplate

**Comment by Ashutosh9993** [comment]
Claim

**Comment by Ashutosh9993** [comment]
Claim

**Comment by Harshal5167** [comment]
claim

**Comment by PranavBansal21** [comment]
claim

**Comment by 0mBudsMan** [comment]
Harshal and Pranav, since this is a first come first serve issue, i'm not able to assign this to you. However, more issues will be rolled out soon enough. Stay tuned on discord for same! Happy contributing

**Comment by 0mBudsMan** [comment]
Ashutosh, make sure the issue gets done in 48 hours! Do ping for any help (on discord)!

**Comment by shashankpatil28** [comment]
can u give me the status @Ashutosh9993 ??

**Comment by CodinJack** [comment]
claim

**Comment by kushal7201** [comment]
claim

**Comment by ShauryaJain03** [comment]
claim

**Comment by 0mBudsMan** [comment]
> claim

Kindky get this done in 12 hours!

**Comment by 0mBudsMan** [comment]
Kindly allign it with my figma! The home page should be of fixed width and the carousel should move on clicking arrow as showin in figma

**Comment by 0mBudsMan** [comment]
Also, I'm not able to see carousel, it's just a series of cards that I'm seeing. Kidly send ss of what it looks like from your screen

**Comment by CodinJack** [comment]
I'm finding it difficult to do the task as i've just recently started react/front-end. Please unassign me the task :(

**Comment by 0mBudsMan** [comment]
Issue reopened for claim

**Comment by captainflatbelly** [comment]
claim

**Comment by 0mBudsMan** [comment]
@harshsingh554 status??

**Comment by LifeAsDev** [comment]
claim

**Comment by 0mBudsMan** [comment]
@LifeAsDev Congrats! Two carousel libraries have already been installed, please make use of one of them to avoid more load in frontend by adding new library. Regards!
