### ISSUE TITLE
Implement Footer Component Using MUI - Figma Design Integration

### ISSUE THREAD

**Issue by 0mBudsMan** [opencodeiiita/Scoop-Frontend#35]
## Title:
"Implement Footer Component Using MUI - Figma Design Integration"

## Description:
###Time: 36 hours
### Issue Description:
Our [Figma](https://www.figma.com/file/vxtYC3QMgjFJ7WTJiorWJ4/Untitled?type=design&node-id=1-3678&mode=design&t=TmG2DqxEwwEr3dLQ-0) design includes a footer section, and we need contributors to implement this footer in the "Footer.js" component. The goal is to utilize MUI (Material-UI) components and shape them according to the provided Figma design. The categories array and comments array have been updated in the "Footer.js" file.
For responsiveness, check how the footer appears on different screens in figma design. For instance, there is no place for categories section in mobile view

### Proposed Changes:
- Utilize MUI components to construct the footer section based on the Figma design.
- Implement the updated categories array and comments array within the "Footer.js" file.
- Ensure that the footer visually aligns with the Figma design, including styling and layout.
- **ENSURE RESPONSIVENESS**

### Additional Information:
- Contributors are encouraged to explore MUI components available on the web for any additional elements needed in the footer.
- Shape the components according to the details provided in the Figma design, paying attention to styling and responsiveness.

### Acceptance Criteria:
- The footer component, implemented using MUI components, should faithfully represent the Figma design for the "Footer.js" component.
- Incorporate the updated categories array and comments array as specified in the "Footer.js" file.
- Thoroughly test the footer for responsiveness and visual fidelity.

Happy Coding!

**Comment by PranavBansal21** [comment]
Claim

**Comment by parimal-10** [comment]
claim

**Comment by optimus-pride** [comment]
claim

**Comment by Nandinig24** [comment]
Claim

**Comment by iam-buddhi** [comment]
claim

**Comment by amanrubey** [comment]
claim

**Comment by PranavBansal21** [comment]
unassign me

**Comment by rnavaneeth992** [comment]
claim

**Comment by rnavaneeth992** [comment]
claim

**Comment by parimal-10** [comment]
claim

**Comment by CodinJack** [comment]
claim

**Comment by ShauryaJain03** [comment]
claim

**Comment by 0mBudsMan** [comment]
> claim

Sorry, you can be assigned only one task per repo as per opencode rules

**Comment by 0mBudsMan** [comment]
> claim

Sorry, you can be assigned only one task per repo as per opencode rules

**Comment by rnavaneeth992** [comment]
claim

**Comment by 0mBudsMan** [comment]
> claim

Assigned! Ensure you complete it within 12 hours

**Comment by rnavaneeth992** [comment]
> > claim
> 
> Assigned! Ensure you complete it within 12 hours

I will complete it by Trm 2PM

**Comment by AngadManroy** [comment]
Claim

**Comment by Karansenpai** [comment]
claim

**Comment by anshuman-rai-27** [comment]
Claim

**Comment by Rohit-110** [comment]
claim

**Comment by GovindaRohith** [comment]
Claim

**Comment by Nandinig24** [comment]
Claim

**Comment by 0mBudsMan** [comment]
> claim

Ensure that this gets done by tomorrow morning :)

**Comment by Rohit-110** [comment]
c

**Comment by KrishayNair** [comment]
Claim

**Comment by GovindaRohith** [comment]
Claim

**Comment by vanshiz** [comment]
claim
