### ISSUE TITLE
Cards for header

### ISSUE THREAD

**Issue by 0mBudsMan** [opencodeiiita/Scoop-Frontend#4]
**TIME: 48 hours**

- Refer Figma
- In desktop view, there are 3 cards in header, below navbar (The first card reads "How to Drive a Car Safely"
- It is named Single Content in figma
- Implement that in website using MUI (Components can be found on web, modify it vis a vis figma)
- 3 such cards in one line (as shown in figma)
- Hide that in mobile view

**Comment by 0mBudsMan** [comment]
Congrats Harsh! Make sure you complete this in 48 hours. Happy open-sourcie-ing! Do ping in discord for any issues

**Comment by PranavBansal21** [comment]
claim

**Comment by Tulsi5990** [comment]
claim
