### ISSUE TITLE
Integrate MUI-Compatible Carousel for Popular Posts - Figma Design Integration

### ISSUE THREAD

**Issue by 0mBudsMan** [opencodeiiita/Scoop-Frontend#5]
## Title:
"Integrate React-Compatible Carousel for Popular Posts - Figma Design Integration"

### Issue Description:
Our Figma [Figma](https://www.figma.com/file/vxtYC3QMgjFJ7WTJiorWJ4/Untitled?type=design&node-id=0-1&mode=design&t=O8Y89SEztFclfTPN-0) (Refer Popular Posts in Figma design) design mandates a carousel UI for the "PopularPost.js" component, offering users an engaging way to explore popular posts. Contributors are encouraged to implement this carousel using any React-compatible carousel library available on npm. The key is to align the component with the provided Figma design while leveraging existing solutions readily available in the npm ecosystem. **Contributors are supposed to use MUI for cards and any carousel lilbrary for react from npm.**

### Proposed Changes:
- Download and integrate any React-compatible carousel library of your choice from npm into the "PopularPost.js" component.
- Incorporate dummy data, already added in component file, to generate cards within the carousel.
- Ensure that the carousel adheres to the Figma design, encompassing post titles, descriptions, and any associated images.

### Additional Information:
- Contributors have the flexibility to choose from popular React-compatible carousel libraries available on npm.
- Tailor the component to match the Figma design while making use of existing components to streamline development.

### Acceptance Criteria:
- The carousel, implemented using a React-compatible library from npm, should faithfully represent the Figma design for the "PopularPost.js" component.
- Use dummy data to validate the carousel's functionality, ensuring an accurate display of popular posts.
- Thoroughly test across various devices and screen sizes for responsiveness.
- Documentation or comments should indicate the chosen React-compatible carousel library and any adjustments made to align with the design.

**Comment by criticic** [comment]
claim

**Comment by ShauryaJain03** [comment]
claim

**Comment by parimal-10** [comment]
claim

**Comment by Nandinig24** [comment]
Claim

**Comment by criticic** [comment]
@0mBudsMan Sorry, I'd like to unassign myself

**Comment by ShauryaJain03** [comment]
@0mBudsMan assign it to me as I was the 2nd one to comment.

**Comment by Nivedh-Biju** [comment]
claim

**Comment by 0mBudsMan** [comment]
Good luck Shaurya! Ping if you have any doubts! Ensure you complete this before 48 hours, so you can claim more issues!!

**Comment by ShauryaJain03** [comment]
Thank you @0mBudsMan!
