### ISSUE TITLE
Crafting Brilliance - Make a Component for Displaying Latest Scoop( news ) in Home Page

### ISSUE THREAD

**Issue by 0mBudsMan** [opencodeiiita/Scoop-Frontend#77]
## Latest News Component

**Type:** Feature

**TIME:** 24 hours

**Description:**
https://www.figma.com/file/I0q9Bcuro7zNKxoSbbLZqu/Untitled?type=design&node-id=223-2&mode=design&t=55RZunjQF7dWANxB-0

This issue requests the development of a reusable component to display the latest news with a hover effect that lifts the card slightly. Use MUI for the same. Font used: Mark pro

**Design:**

- Refer to the attached image and figma for the visual layout and styling.

**Requirements:**

* Implement a design similar to that shown
* Two screens are attached, one for mobile/tablet and one for desktop
* Implement a subtle hover effect that elevates the card (by a little amount) on hover.

![MOBILETABLET](https://github.com/opencodeiiita/Scoop-Frontend/assets/128999558/101bcb15-7eab-4bfc-8136-54b36741d3f1)
![DESKTOP](https://github.com/opencodeiiita/Scoop-Frontend/assets/128999558/f671ceb7-cec3-4120-8574-4b5e2c949507)

* Feel free to discuss any questions or challenges related to this issue in the comments section.
* Open pull requests with your proposed implementations for review and feedback.

**Comment by captainflatbelly** [comment]
claim

**Comment by 0mBudsMan** [comment]
COngrats Harsh

**Comment by 0mBudsMan** [comment]
@harshsingh554 status?

**Comment by chiragmalik2612** [comment]
Claim

**Comment by ssugam10** [comment]
claim

**Comment by Rohit-110** [comment]
claim

**Comment by 0mBudsMan** [comment]
Congrats @chiragmalik2612 !!

**Comment by Apoorv012** [comment]
claim

**Comment by abhisheksharma010** [comment]
Claim
