### ISSUE TITLE
Making an Account Management Section

### ISSUE THREAD

**Issue by 0mBudsMan** [opencodeiiita/Scoop-Frontend#81]
### Description

We are looking to implement the account management section in our application, based on the design provided in Figma. This issue specifically focuses on the first section of the page. The second section will be addressed in a separate issue.

### Figma Design

[Account Management Section - Figma Design](https://www.figma.com/file/I0q9Bcuro7zNKxoSbbLZqu/Untitled?type=design&node-id=36-2&mode=design&t=XBCXrdwLrKNxhg5x-0)

#### 1. Implement First Section (Account Details)

- [ ] Create the structure for the account management page.
- [ ] Apply the styles as per the Figma design for the first section.
- [ ] Ensure responsiveness for different screen sizes.
- [ ] Integrate MUI and use it's components.
- [ ] Screens for laptop/tablet and mobile have been given in figma

#### 2. Second Section (Account activity) (Leave Blank for Now)

- [ ] Just display 'second section' there

### Guidelines

- Refer to the Figma design for accurate styling and layout.

- Follow responsive design principles to ensure a consistent experience on various devices.
- Don't create different pages, just these two sections in one page, and give section1 and section2 its corresponding id.
- When scrolled to id section2, make sure the bar in the left side changes, so that displayed section is Account Activvity 

### Deadline

36 hours

###FONT: https://dwl.freefontsfamily.com/download/ff-mark-font/

**Comment by Karansenpai** [comment]
Claim

**Comment by Karansenpai** [comment]
> Collaborator

The figma link only contain the screenshot. Can u provide the actual layout of page .

**Comment by 0mBudsMan** [comment]
@Karansenpai I'll not be able to provide you the actual layout. I have provided the font to be used. For colors, you can pick color closest to the attached design

**Comment by chiragmalik2612** [comment]
still opened ? claim
