### ISSUE TITLE
Bug Fix

### ISSUE THREAD

**Issue by 0mBudsMan** [opencodeiiita/Scoop-Frontend#82]
### Description

The current implementation of the website results in content extending beyond the viewport width, causing an unwanted horizontal scrollbar. This issue aims to fix the bug by ensuring that the contents occupy only 100vw (100% of the screen's width) and prevent any overflow.

### Bug Symptoms

- Horizontal scrollbar visible on the website.
- Content extends beyond the viewport width.

### Steps to Reproduce

1. Open the website.
2. Observe the horizontal scrollbar and content extending beyond the viewport.

### Expected Behavior

The website content should be contained within the viewport width (100vw), eliminating the need for a horizontal scrollbar.

### Additional Information

- If you encounter any challenges or need clarification on the bug fix, feel free to ask in the comments.
- Make sure to test the fix thoroughly on various devices and browsers.

### Deadline: 24 hours

Let's ensure the website displays correctly within the viewport width! 🛠️

**Comment by WadadParker** [comment]
since this is a bug fix can you make it open for all so that best PR can be merged?

**Comment by 0mBudsMan** [comment]
@WadadParker Yes, sounds good!!

**Comment by ssugam10** [comment]
claim

**Comment by Rohit-110** [comment]
claim

**Comment by 0mBudsMan** [comment]
@Rohit-110 no need to claim! It is open for all
