### ISSUE TITLE
Composing Beauty! Make a Profile Page as Shown In Figma

### ISSUE THREAD

**Issue by 0mBudsMan** [opencodeiiita/Scoop-Frontend#92]
**REFER TO FIGMA LINK PROVIDED BELOW AND MAKE A SIMILAR PROFILE  PAGE**
[https://www.figma.com/file/vxtYC3QMgjFJ7WTJiorWJ4/Untitled?type=design&node-id=0-1&mode=design&t=CeeZmROAML2MIjPM-0](url)

**Comment by chiragmalik2612** [comment]
claim

**Comment by Rohit-110** [comment]
claim

**Comment by 0mBudsMan** [comment]
@chiragmalik2612 sorry, one person can work on only one repo at a time

**Comment by chiragmalik2612** [comment]
@0mBudsMan  that's almost complete i show you

**Comment by chiragmalik2612** [comment]
till 11am i'll make PR @0mBudsMan

**Comment by 0mBudsMan** [comment]
@chiragmalik2612 abiding the rules of opencode, I'm unable to assign this to you. However, nothing to worry, many more exciting issues await!! Happy coding

**Comment by kushal7201** [comment]
Claim

**Comment by Rohit-110** [comment]
I unassigned myself since the pr was merged
