### ISSUE TITLE
Crafting a Figma-Inspired Scoop Display Page with Artistic Precision

### ISSUE THREAD

**Issue by 0mBudsMan** [opencodeiiita/Scoop-Frontend#94]
# Task: Create Page for Displaying Scoop (News)

### Goal
Design and implement a page for displaying news scoops on the frontend. You will receive the necessary data from the backend, and the model structure is defined as follows: 

1. **Headline**: The headline of the news.
2. **Location**: The geographical location associated with the news.
3. **Description**: A string containing HTML for rendering the news description on the frontend.
4. **Tags**: An array of strings representing tags associated with the news.
5. **Upvote Count**: The count of upvotes received for the news.
6. **User**: Information about the user who posted the news.
7. **Comments**: An array of strings representing comments associated with the news.

### Design Considerations
- The font to be used in the HTML rendering should match the font used in the [Figma](https://www.figma.com/file/vxtYC3QMgjFJ7WTJiorWJ4/Untitled?type=design&node-id=0-1&mode=design&t=MRFfC2kcJwecgztS-0) design (named scoop). Refer to the Figma design for font details.

### Data Model
**An instance of the above data model is provided on the `scoop.js` page in the project. Please make use of this model for consistency and integration.**

### Tasks

1. **Create Scoop Display Page**
   - Design and implement a page dedicated to displaying news scoops.

2. **Integrate Backend Data**
   - Fetch news data from the backend using the provided object in /pages/scoop.js

3. **Render HTML Description with Figma Font**
   - Ensure proper rendering of the HTML string received in the news description **using the font specified in the Figma design.**

4. **Utilize Provided Model**
   - Use the provided instance of the data model from the `displaynews` page for consistency.

### Additional Information
- Ensure a clean and user-friendly design for the scoop display page.
- Implement responsiveness for various screen sizes.

## Deadline
Please submit your pull request by [36 hrs].

**Note:** Feel free to ask for any clarifications or assistance during the implementation process.

**Comment by WadadParker** [comment]
claim

**Comment by 0mBudsMan** [comment]
congrats @WadadParker

**Comment by 0mBudsMan** [comment]
@WadadParker kindly make this done fast! You're already past time
