### ISSUE TITLE
Design and Implement Page for Displaying All News 

### ISSUE THREAD

**Issue by 0mBudsMan** [opencodeiiita/Scoop-Frontend#99]
# Task: Design and Implement Page for Displaying All News (Scoop)

### Goal
Create a visually appealing page for displaying all news scoops on the frontend. The Figma design is attached for reference.

### Design Considerations
- Refer to the attached Figma design for layout, colors, and styling details.
- In desktop/tablet view, display two news cards in one line.
- In mobile view, display one news card per line.

### Figma Design
[Figma Design - News Display](https://www.figma.com/file/I0q9Bcuro7zNKxoSbbLZqu/Untitled?type=design&node-id=0-1&mode=design&t=lmkxl3iPy3qrVjwP-0)

### Tasks

1. **Create News Display Page**
   - Design and implement a page dedicated to displaying all news scoops.

2. **Responsive Layout**
   - Implement a responsive layout:
     - In desktop/tablet view, display two news cards in one line.
     - In mobile view, display one news card per line.

3. **Apply Figma Styling**
   - Apply the styling details from the Figma design to ensure visual consistency.

### Additional Information
- Ensure a clean and user-friendly design for the news display page.
- Implement responsiveness for various screen sizes.

## Deadline
Please submit your pull request by [24 hours].

**Note:** Feel free to ask for any clarifications or assistance during the implementation process.

**Comment by Karansenpai** [comment]
Claim

**Comment by abhisheksharma010** [comment]
- claim

**Comment by Karansenpai** [comment]
figma link doesn't have allnews page

**Comment by 0mBudsMan** [comment]
@Karansenpai someone removed that by mistake, check it now
